---
image: geerlingguy/docker-centos7-ansible:latest

before_script:
  - scripts/setup.sh
test:
  script:
    - ansible-galaxy install -r requirements.yml
    - export PATH=$PATH:/opt/mssql-tools/bin
    - ansible-playbook -i scripts/hosts dbclient.yml -e "testing=True"
  only:
    - master
    - dev
