---
image: geerlingguy/docker-centos7-ansible:latest

before_script:
  - scripts/setup.sh
test:
  script:
    - ansible-galaxy install -r requirements.yml
    - ls -l roles/
    - ansible-playbook -i scripts/hosts dbclient.yml
    - export PATH=$PATH:/opt/mssql-tools/bin
    - which /usr/bin/sqlcmd
    - exit 0
  only:
    - dev
