language: generic
install:
  - scripts/setup.sh
script:
  - ansible-galaxy install -r requirements.yml
  - export PATH=$PATH:/opt/mssql-tools/bin
  #- ansible-playbook -i scripts/hosts dbclient.yml -e "testing=True"
  - SA_PASSWORD='1AMa_secret_Passw0rd2017' ansible-playbook -i scripts/hosts dbserver.yml -e "testing=True"
sudo: sudo 
