---

- name: Check if sql server is running
  command: systemctl status mssql-server
  ignore_errors: True
  register: sqlserver_service

- name: Stop sql server if it was already running and initialized
  service: name=mssql-server state=stopped
  when: sqlserver_service.stdout.find('running') == -1

- name: Initial setup of sql server
  command: /opt/mssql/lib/mssql-conf/mssql-conf.py setup accept-eula
  when: sqlserver_service.stdout.find('running') == -1

- name: Start sql server
  service: name=mssql-server state=started enabled=yes
  when: sqlserver_service.stdout.find('running') == -1

