---
- name: "Test credstash lookup plugin -- get the secret password"
  debug: msg="Credstash lookup! {{ lookup('credstash', 'SA') }}"

- name: "Test password store"
  debug: msg="{{ lookup('pipe', 'pass MSSQL/{{inventory_hostname}}/SA') }}"
